export const GRID_PHOTO_CLASSES=[
    'catImgBreedsDiv1',
    'catImgBreedsDiv2',
    'catImgBreedsDiv3',
    'catImgBreedsDiv4',
    'catImgBreedsDiv5',
    'catImgBreedsDiv6',
    'catImgBreedsDiv7',
    'catImgBreedsDiv8',
    'catImgBreedsDiv9',
    'catImgBreedsDiv10',
    'catImgBreedsDiv11',
    'catImgBreedsDiv12',
    'catImgBreedsDiv13',
    'catImgBreedsDiv14',
    'catImgBreedsDiv15',
]
