export const CATS_URL='https://api.thecatapi.com/v1/images/search'
export const CATS_URL_BY_BREEDS='https://api.thecatapi.com/v1/images/search?breed_ids='
export const IMG_INFO='https://api.thecatapi.com/v1/breeds'
export const IMG_BY_ID='https://api.thecatapi.com/v1/images/'
export const API_KEY = 'live_v4sgD89giJAODf8CxClwlUZxBeAoUyKMuSQ0dstBAI13CLIUwl6kxJX2aeQpnVAW'